#!/usr/bin/with-contenv bash
# shellcheck shell=bash
RUNUSER=${RUNUSER:-alpine}

# create folders
mkdir -p \
	/config \
    /data

# permissions
lsiown -R $RUNUSER:$RUNUSER \
	/config \
    /data

if [ $(stat -c '%a' /config) -lt 700 ]; then
    chmod 755 /config \
    /data
fi
